# Goreleaser configuration for PayloadGo Enterprise
project_name: payloadgo
before:
  hooks:
    - go mod tidy
    - go mod verify
    - go vet ./...
    - go test ./...

builds:
  - id: payloadgo
    binary: payloadgo
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0

archives:
  - id: payloadgo
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - README.md
      - LICENSE
      - configs/
      - examples/
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - id: payloadgo
    image_templates:
      - "payloadgo/payloadgo:{{ .Version }}"
      - "payloadgo/payloadgo:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - --label=org.opencontainers.image.title=PayloadGo Enterprise
      - --label=org.opencontainers.image.description=Enterprise-grade security testing platform
      - --label=org.opencontainers.image.vendor=PayloadGo
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .Commit }}

snapcrafts:
  - id: payloadgo
    name: payloadgo
    summary: Enterprise security testing platform
    description: |
      PayloadGo Enterprise is a comprehensive security testing platform
      designed for enterprise environments with advanced features like
      multi-tenancy, RBAC, audit logging, and enterprise reporting.
    grade: stable
    confinement: strict
    apps:
      payloadgo:
        command: payloadgo
        plugs:
          - network
          - network-bind
          - home
          - removable-media

brews:
  - name: payloadgo
    description: Enterprise security testing platform
    homepage: https://github.com/payloadgo/payloadgo
    license: "MIT"
    test: |
      system "#{bin}/payloadgo version"
    install: |
      bin.install "payloadgo"

nfpms:
  - id: payloadgo
    package_name: payloadgo
    maintainer: PayloadGo Team <team@payloadgo.com>
    description: Enterprise security testing platform
    homepage: https://github.com/payloadgo/payloadgo
    license: MIT
    vendor: PayloadGo
    formats:
      - deb
      - rpm
    contents:
      - src: README.md
        dst: /usr/share/doc/payloadgo/
      - src: configs/
        dst: /etc/payloadgo/
      - src: examples/
        dst: /usr/share/payloadgo/examples/
    scripts:
      postinstall: scripts/postinstall.sh
      preremove: scripts/preremove.sh

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: payloadgo
    name: payloadgo
  draft: false
  prerelease: auto
  name_template: "PayloadGo Enterprise {{ .Version }}"
  body: |
    ## PayloadGo Enterprise {{ .Version }}
    
    ### What's New
    {{ range .Changes }}
    - {{ .Commit.Message }}
    {{ end }}
    
    ### Installation
    
    #### Binary Downloads
    Download the appropriate binary for your platform from the assets below.
    
    #### Docker
    ```bash
    docker pull payloadgo/payloadgo:{{ .Version }}
    ```
    
    #### Homebrew (macOS)
    ```bash
    brew install payloadgo/payloadgo/payloadgo
    ```
    
    #### APT (Ubuntu/Debian)
    ```bash
    wget https://github.com/payloadgo/payloadgo/releases/download/{{ .Version }}/payloadgo_{{ .Version }}_linux_amd64.deb
    sudo dpkg -i payloadgo_{{ .Version }}_linux_amd64.deb
    ```
    
    #### YUM (RHEL/CentOS)
    ```bash
    wget https://github.com/payloadgo/payloadgo/releases/download/{{ .Version }}/payloadgo-{{ .Version }}-1.x86_64.rpm
    sudo rpm -i payloadgo-{{ .Version }}-1.x86_64.rpm
    ```

announce:
  skip: false
  twitter:
    enabled: true
    message_template: "🚀 PayloadGo Enterprise {{ .Version }} is out! {{ .Changelog }}"
  discord:
    enabled: true
    message_template: "🚀 PayloadGo Enterprise {{ .Version }} is out! {{ .Changelog }}"
  slack:
    enabled: true
    message_template: "🚀 PayloadGo Enterprise {{ .Version }} is out! {{ .Changelog }}"