# PayloadGo Configuration File
# This file contains default configuration for PayloadGo

# Concurrency settings
threads: 10                    # Number of concurrent threads
timeout: 10                    # Request timeout in seconds
rate_limit: 10                 # Requests per second limit

# Network settings
proxy: ""                      # Proxy URL (e.g., http://127.0.0.1:8080)
user_agent: "PayloadGo/1.0"   # Custom user agent string

# Output settings
verbose: false                 # Verbose output
save_responses: false          # Save response bodies in reports
output_format: "json"          # Default output format (json, html, txt)

# Logging settings
log_level: "INFO"              # Log level (DEBUG, INFO, WARN, ERROR)
log_file: ""                   # Log file path (empty for stdout)

# Advanced settings
max_redirects: 5               # Maximum number of redirects to follow
follow_redirects: true          # Follow HTTP redirects
verify_ssl: true               # Verify SSL certificates
retry_attempts: 3              # Number of retry attempts for failed requests
retry_delay: 1                 # Delay between retries in seconds

# Payload settings
payload_categories:            # Default payload categories to test
  - "xss"
  - "sqli"
  - "xxe"
  - "path_traversal"
  - "command_injection"

# Custom headers
custom_headers:
  "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
  "Accept-Language": "en-US,en;q=0.5"
  "Accept-Encoding": "gzip, deflate"
  "Connection": "keep-alive"

# Report settings
report_template: ""            # Custom report template file
include_timeline: true          # Include timeline in reports
include_statistics: true       # Include statistics in reports
group_by_type: true            # Group vulnerabilities by type in reports

# Security settings
stealth_mode: false            # Enable stealth mode (slower, more random)
randomize_payloads: false      # Randomize payload order
delay_between_requests: 0      # Delay between requests in milliseconds
